const assert=require('node:assert/strict'),{spawn}=require('node:child_process'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{const server=spawn('python3',['-m','http.server','8771'],{cwd:path.resolve(__dirname,'..'),stdio:'ignore'});await new Promise(r=>setTimeout(r,300));const browser=await chromium.launch({executablePath:process.env.INFO1_TEST_CHROME,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader']});try{
 const p=await browser.newPage();await p.route('**/cloud-test',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><body>Cloud regression</body>'}));await p.goto('http://127.0.0.1:8771/cloud-test');await p.addScriptTag({url:'/notebook-merge.js'});
 await p.evaluate(()=>{
  const key='info1-study-center-v4-priority',mem=new Map(),copy=x=>JSON.parse(JSON.stringify(x));window.testKey=key;
  window.INFO1_LOCAL={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
  window.remote={state:{a:0,b:0,__notebooksV1:{notebooks:{},order:[]}},revision:1};INFO1_LOCAL.setItem(key,JSON.stringify(remote.state));window.INFO1_WAS_LOCAL_STATE=true;
  window.readDelay=0;window.writeDelay=0;window.writes=0;window.casMiss=false;window.onWrite=null;
  const user={id:'test',user_metadata:{info1_workspace_id:'ws'}},auth={getSession:async()=>({data:{session:{user}}}),getUser:async()=>({data:{user}}),onAuthStateChange(){}};
  const client={auth,removeChannel:async()=>{},channel(){const ch={on(t,f,fn){window.remoteEvent=fn;return ch;},subscribe(){return ch;}};return ch;},from(table){let update=null,revision=null;const q={select(){return q;},eq(k,v){if(k==='revision')revision=v;return q;},update(v){update=v;return q;},async maybeSingle(){if(update){window.writes++;window.onWrite?.();await new Promise(r=>setTimeout(r,writeDelay));if(casMiss){casMiss=false;remote.state.b=2;remote.revision++;return {data:null};}if(revision!==remote.revision)return {data:null};remote={state:copy(update.state),revision:update.revision};return{data:{revision:remote.revision}};}const result=copy(remote);await new Promise(r=>setTimeout(r,readDelay));return{data:result};},then(resolve,reject){return Promise.resolve({data:table==='info1_members'?[{workspace_id:'ws',role:'owner',info1_workspaces:{id:'ws',name:'Test'}}]:[]}).then(resolve,reject);}};return q;}};
  window.INFO1_SUPABASE={url:'https://example.com',publishableKey:'test'};window.supabase={createClient:()=>client};
 });await p.addScriptTag({url:'/cloud-sync.js'});await p.waitForFunction(()=>INFO1_CLOUD?.status.connected&&INFO1_LOCAL.getItem('info1-cloud-base:ws'));
 await p.evaluate(()=>{casMiss=true;writeDelay=120;onWrite=()=>{onWrite=null;const s=JSON.parse(INFO1_LOCAL.getItem(testKey));s.c=3;INFO1_LOCAL.setItem(testKey,JSON.stringify(s));};const s=JSON.parse(INFO1_LOCAL.getItem(testKey));s.a=1;INFO1_LOCAL.setItem(testKey,JSON.stringify(s));});
 await p.waitForFunction(()=>remote.state.a===1&&remote.state.b===2&&remote.state.c===3&&!INFO1_CLOUD.status.dirty,{},{timeout:15000});assert.equal(await p.evaluate(()=>INFO1_CLOUD.status.conflict),false);console.log('PASS CAS revision retry and edits during upload preserve both devices');
 await p.evaluate(()=>{readDelay=200;remote.state.b=4;remote.revision++;const pull=INFO1_CLOUD.pull();setTimeout(()=>{const s=JSON.parse(INFO1_LOCAL.getItem(testKey));s.a=5;INFO1_LOCAL.setItem(testKey,JSON.stringify(s));},50);return pull;});
 assert.equal(await p.evaluate(()=>JSON.parse(INFO1_LOCAL.getItem(testKey)).a),5);assert.equal(await p.evaluate(()=>JSON.parse(INFO1_LOCAL.getItem(testKey)).b),4);console.log('PASS local edit during cloud download survives');
 }finally{await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exit(1)});
